### PR TITLE
added solution to problem https://www.codechef.com/COLE2020/problems/…

### PR DESCRIPTION
**Pull request by rahulbollisetty**
…CLLCM

### CODE REVIEW

**Comment by rahulbollisetty** [comment]
mam is there any cap for adding solutions?

**Comment by diyajaiswal11** [comment]
Sorry didn't understand you. cap?

**Comment by rahulbollisetty** [comment]
i mean is there any limit for prs in this repo?
can i pull as many PRs as possible

**Comment by diyajaiswal11** [comment]
No, no limit. You can make as many as PRs as you feel like. :)

**Pull request merged**
